#!/usr/bin/env pwsh
# Copilot Agents Dojo - Lesson Updater
# Scans tasks/lessons.md for recurring patterns and proposes amendments to skills.md.
#
# Usage: pwsh scripts/lesson-updater.ps1
#
# What it does:
#   1. Parses lessons.md for entries with occurrences >= 3
#   2. Groups by error_type
#   3. Outputs proposed rule amendments for skills.md
#   4. Optionally appends proposals to a review file

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$ScriptDir = $PSScriptRoot
$RepoRoot = Split-Path -Parent $ScriptDir
$LessonsFile = Join-Path $RepoRoot 'tasks/lessons.md'
$SkillsFile = Join-Path $RepoRoot 'skills.md'
$ProposalsFile = Join-Path $RepoRoot 'tasks/proposed-amendments.md'

if (-not (Test-Path -LiteralPath $LessonsFile -PathType Leaf)) {
    Write-Host "❌ No lessons.md found at $LessonsFile"
    Write-Host "   Run scripts/init.sh first."
    exit 1
}

Write-Host "🥋 Copilot Agents Dojo - Lesson Updater"
Write-Host "   Scanning $LessonsFile for recurring patterns..."
Write-Host ""

$lines = Get-Content -LiteralPath $LessonsFile
$recurring = New-Object System.Collections.Generic.List[string]

for ($i = 0; $i -lt $lines.Count; $i++) {
    $line = $lines[$i]
    if ($line -match 'occurrences:\s*(\d+)') {
        $occurrences = [int]$Matches[1]
        if ($occurrences -ge 3) {
            $windowEnd = [Math]::Min($i + 6, $lines.Count - 1)
            $errorTypeLine = $null
            $ruleLine = $null

            for ($j = $i; $j -le $windowEnd; $j++) {
                if (-not $errorTypeLine -and $lines[$j] -match 'error_type:') {
                    $errorTypeLine = $lines[$j].Trim()
                }
                if (-not $ruleLine -and $lines[$j] -match 'rule:') {
                    $ruleLine = $lines[$j].Trim()
                }
            }

            if ($errorTypeLine) {
                $recurring.Add($errorTypeLine)
            }
            if ($ruleLine) {
                $recurring.Add($ruleLine)
                $recurring.Add('---')
            }
        }
    }
}

if ($recurring.Count -eq 0) {
    Write-Host "✅ No recurring patterns (3+ occurrences) found."
    Write-Host "   Your agents are learning well - or lessons need more data."
    exit 0
}

Write-Host "⚠️  Recurring patterns detected:"
Write-Host ""
$recurringText = ($recurring -join [Environment]::NewLine)
Write-Host $recurringText
Write-Host ""

$timestamp = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')
$proposal = @"
# Proposed Skill Amendments

> Auto-generated by lesson-updater.ps1 on $timestamp
> Review these and manually merge approved rules into skills.md.

## Recurring Patterns

$recurringText

## Action Items
- [ ] Review each pattern above
- [ ] Add approved rules to the relevant section in skills.md
- [ ] Update lesson entries with status: amended-to-skill
- [ ] Update metrics in lessons.md
"@

$proposal | Set-Content -LiteralPath $ProposalsFile -Encoding UTF8

Write-Host "📝 Proposals written to tasks/proposed-amendments.md"
Write-Host "   Review and merge approved rules into skills.md."
