#!/usr/bin/env bash
# Copilot Agents Dojo — Lesson Updater
# Scans tasks/lessons.md for recurring patterns and proposes amendments to skills.md.
#
# Usage: bash scripts/lesson-updater.sh
#
# What it does:
#   1. Parses lessons.md for entries with occurrences >= 3
#   2. Groups by error_type
#   3. Outputs proposed rule amendments for skills.md
#   4. Optionally appends proposals to a review file

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
LESSONS_FILE="$REPO_ROOT/tasks/lessons.md"
SKILLS_FILE="$REPO_ROOT/skills.md"
PROPOSALS_FILE="$REPO_ROOT/tasks/proposed-amendments.md"

if [ ! -f "$LESSONS_FILE" ]; then
  echo "❌ No lessons.md found at $LESSONS_FILE"
  echo "   Run scripts/init.sh first."
  exit 1
fi

echo "🥋 Copilot Agents Dojo — Lesson Updater"
echo "   Scanning $LESSONS_FILE for recurring patterns..."
echo ""

# Extract entries with occurrences >= 3
RECURRING=$(grep -A 6 'occurrences:' "$LESSONS_FILE" | \
  awk '/occurrences:/ { split($0, a, ":"); gsub(/[^0-9]/, "", a[2]); if (a[2]+0 >= 3) found=1; else found=0 }
       /error_type:/ && found { print $0 }
       /rule:/ && found { print $0; print "---" }' 2>/dev/null || true)

if [ -z "$RECURRING" ]; then
  echo "✅ No recurring patterns (3+ occurrences) found."
  echo "   Your agents are learning well — or lessons need more data."
  exit 0
fi

echo "⚠️  Recurring patterns detected:"
echo ""
echo "$RECURRING"
echo ""

# Write proposals file
cat > "$PROPOSALS_FILE" << EOF
# Proposed Skill Amendments

> Auto-generated by lesson-updater.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
> Review these and manually merge approved rules into skills.md.

## Recurring Patterns

$RECURRING

## Action Items
- [ ] Review each pattern above
- [ ] Add approved rules to the relevant section in skills.md
- [ ] Update lesson entries with \`status: amended-to-skill\`
- [ ] Update metrics in lessons.md
EOF

echo "📝 Proposals written to tasks/proposed-amendments.md"
echo "   Review and merge approved rules into skills.md."
