name: Update latest blog posts (self-hosted)

on:
  schedule:
    - cron: "30 5 * * *"   # 05:30 UTC ≈ 07:30 Europe/Brussels (most of the year)
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Update README from RSS
        run: |
          python scripts/update_blog_posts.py --verbose

      - name: Commit changes if any
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore(readme): update latest blog posts"
            git push
          else
            echo "No changes to commit."
          fi