name: Generate thumbnails (100x100 + icons 40x40)

on:
  push:
    paths:
      - "assets/**"
  workflow_dispatch: {}

jobs:
  thumbs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ImageMagick (with SVG support)
        run: |
          sudo apt-get update
          sudo apt-get install -y imagemagick librsvg2-bin

      - name: Create 100x100 thumbnails for all PNGs (crop to square, keep transparency)
        run: |
          shopt -s globstar nullglob
          changed=0
          for img in assets/**/*.png; do
            [[ "$img" =~ -100x100\.png$ ]] && continue
            [[ "$img" =~ -40x40\.png$ ]] && continue
            out="${img%.png}-100x100.png"
            # Keep alpha, set background to transparent BEFORE extent
            convert "$img" \
              -alpha on -background none \
              -thumbnail 100x100^ -gravity center -extent 100x100 \
              -strip -define png:color-type=6 "$out"
            if [[ -f "$out" ]]; then
              echo "Created: $out"
              changed=1
            fi
          done
          echo "CHANGED=$changed" >> $GITHUB_ENV

      - name: Create 40x40 icons in assets/icons (PNG & SVG), keep transparency
        run: |
          shopt -s nullglob
          changed=${CHANGED:-0}

          # PNG icon sources
          for img in assets/icons/*.png; do
            [[ "$img" =~ -40x40\.png$ ]] && continue
            [[ "$img" =~ -100x100\.png$ ]] && continue
            out="${img%.png}-40x40.png"
            convert "$img" \
              -alpha on -background none \
              -thumbnail 40x40^ -gravity center -extent 40x40 \
              -strip -define png:color-type=6 "$out"
            if [[ -f "$out" ]]; then
              echo "Created: $out"
              changed=1
            fi
          done

          # SVG icon sources → PNG 40x40
          for svg in assets/icons/*.svg; do
            [[ "$svg" =~ -40x40\.svg$ ]] && continue
            [[ "$svg" =~ -100x100\.svg$ ]] && continue
            base="${svg%.svg}"
            out="${base}-40x40.png"
            [[ -f "$out" ]] && continue

            if command -v rsvg-convert >/dev/null 2>&1; then
              # Keep transparency with rsvg-convert
              rsvg-convert -w 40 -h 40 -b transparent "$svg" -o "$out"
            else
              # Fallback: ImageMagick conversion with transparent background
              convert -background none -alpha on -resize 40x40 "$svg" "$out"
            fi

            if [[ -f "$out" ]]; then
              echo "Created: $out"
              changed=1
            fi
          done

          echo "CHANGED=$changed" >> $GITHUB_ENV


      - name: Commit thumbnails (if any)
        if: env.CHANGED == '1'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/**/*-100x100.png assets/icons/*-40x40.png
          git commit -m "chore(assets): add 100x100 and 40x40 thumbnails"
          git push
